alphabet: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ
cls_loss: LISTER_INTERNAL
epoch_max: 500
force_lr: true
func_train: SROCR_TRAIN
func_val: SROCR_VAL
loss:
  args: {}
  name: SROCR_loss
model_g:
  args:
    in_channels: 3
    max_len: 7
    num_classes: 37
  name: LISTER_BASELINE
name: LISTER_BASELINE_Curriculum
optimizer_sr:
  args:
    lr: 1e-4
  name: adamW
resume: null
train_dataset:
  batch: 64
  dataset:
    args:
      in_memory: true
      path_split: ./CompetitionDataset_LMDB_plus
      phase: training
    name: lmdb_dataset
  wrapper:
    args:
      anagram_prob: 0.0
      aug: true
      background: (127, 127, 127)
      fully_synthetic_prob: 0.0
      image_aspect_ratio: 3.0
      imgH: 24
      imgW: 72
      in_images: 1
      synthetic_prob: 0.0
    name: VSR_collate_fn
use_fp16: true
val_dataset:
  batch: 64
  dataset:
    args:
      in_memory: true
      path_split: ./CompetitionDataset_LMDB_plus
      phase: validation
    name: lmdb_dataset
  wrapper:
    args:
      aug: false
      background: (127, 127, 127)
      fully_synthetic_prob: 0.0
      image_aspect_ratio: 3.0
      imgH: 24
      imgW: 72
      in_images: 5
      synthetic_prob: 0.0
      test: true
    name: VSR_Sequence_collate_fn
