name: OTE_BASELINE_Curriculum
alphabet: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ
cls_loss: OTE              

epoch_max: 500
force_lr: true
func_train: SROCR_TRAIN
func_val: SROCR_VAL
use_fp16: true
resume: null

model_g:
  name: OTE_BASELINE
  args:
    in_channels: 3
    max_len: 7
    num_classes: 37

optimizer_sr:
  name: adamW
  args:
    lr: 1e-4

LRScheduler:
  name: OneCycleLR
  warmup_epoch: 1.5 # pct_start 0.075*20 = 1.5ep
  cycle_momentum: False

# ==========================================================
# DATALOADERS
# ==========================================================
train_dataset:
  batch: 64
  dataset:
    name: lmdb_dataset
    args:
      in_memory: true
      path_split: ./competition_dataset_lmdb
      phase: training
  wrapper:
    name: VSR_collate_fn
    args:
      anagram_prob: 0.0
      aug: true
      background: (127, 127, 127)
      fully_synthetic_prob: 0.0
      image_aspect_ratio: 3.0
      imgH: 32  
      imgW: 96  
      in_images: 1
      synthetic_prob: 0.0

val_dataset:
  batch: 64 
  dataset:
    name: lmdb_dataset
    args:
      in_memory: true
      path_split: ./competition_dataset_lmdb
      phase: validation
  wrapper:
    name: VSR_Sequence_collate_fn
    args:
      aug: false
      background: (127, 127, 127)
      fully_synthetic_prob: 0.0
      image_aspect_ratio: 3.0
      imgH: 32  
      imgW: 96  
      in_images: 5
      synthetic_prob: 0.0
      test: true
