alphabet: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ
distill_decay_epochs: 50
epoch_max: 3000
epoch_save: 50
force_lr: false
func_train: SROCR_TRAIN
func_val: SROCR_VAL


cls_loss: CTC              
model_g:
  name: SVTRV2_BASELINE
  args:
    num_classes: 38

LRScheduler:
  name: CosineAnnealingLR

name: VSR_FeatureOCR_Curriculum
optimizer_sr:
  args:
    betas:
    - 0.9
    - 0.999
    lr: 1e-4
    weight_decay: 0.0
  name: adamW
resume: null
train_dataset:
  batch: 64
  dataset:
    args:
      in_memory: true
      path_split: ./competition_dataset_lmdb
      phase: training
    name: lmdb_dataset
  wrapper:
    args:
      anagram_prob: 0.0
      aug: true
      background: (127, 127, 127)
      fully_synthetic_prob: 0.0
      image_aspect_ratio: 3.0
      imgH: 32
      imgW: 96
      in_images: 1
      synthetic_prob: 0.0
    name: VSR_collate_fn
use_fp16: true
val_dataset:
  batch: 64
  dataset:
    args:
      in_memory: true
      path_split: ./competition_dataset_lmdb
      phase: validation
    name: lmdb_dataset
  wrapper:
    args:
      aug: false
      background: (127, 127, 127)
      fully_synthetic_prob: 0.0
      image_aspect_ratio: 3.0
      imgH: 32
      imgW: 96
      in_images: 5
      synthetic_prob: 0.0
      test: true
    name: VSR_Sequence_collate_fn
warmup_epochs: 0
